
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.allaboutengie.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.allaboutengie.item.YouAreNotSupposedToHaveThisItem;
import net.mcreator.allaboutengie.item.UnobtaniumItem;
import net.mcreator.allaboutengie.item.UnobtainiumSwordItem;
import net.mcreator.allaboutengie.item.UnobtainiumShovelItem;
import net.mcreator.allaboutengie.item.UnobtainiumPickaxeItem;
import net.mcreator.allaboutengie.item.UnobtainiumItem;
import net.mcreator.allaboutengie.item.UnobtainiumHoeItem;
import net.mcreator.allaboutengie.item.UnobtainiumChunkletItem;
import net.mcreator.allaboutengie.item.UnobtainiumAxeItem;
import net.mcreator.allaboutengie.item.UncookedPizzaItem;
import net.mcreator.allaboutengie.item.UncommonSwordItem;
import net.mcreator.allaboutengie.item.UncommonShovelItem;
import net.mcreator.allaboutengie.item.UncommonPickaxeItem;
import net.mcreator.allaboutengie.item.UncommonItem;
import net.mcreator.allaboutengie.item.UncommonHoeItem;
import net.mcreator.allaboutengie.item.UncommonAxeItem;
import net.mcreator.allaboutengie.item.TrueBanHammerPixelItem;
import net.mcreator.allaboutengie.item.TrueBanHammerNCMDPixelItem;
import net.mcreator.allaboutengie.item.TrueBanHammerNCMDItem;
import net.mcreator.allaboutengie.item.TrueBanHammerItem;
import net.mcreator.allaboutengie.item.TesterItem;
import net.mcreator.allaboutengie.item.TesterEngieBundleItem;
import net.mcreator.allaboutengie.item.SuperDoomsDaysItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayShovelItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayScytheItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayPickaxeItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayHoeItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayCrucifixPixelItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayCrucifixItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayCoinItem;
import net.mcreator.allaboutengie.item.SuperDoomsDayAxeItem;
import net.mcreator.allaboutengie.item.SharkosPlaqueItem;
import net.mcreator.allaboutengie.item.SharkoClothItem;
import net.mcreator.allaboutengie.item.SharkItem;
import net.mcreator.allaboutengie.item.RareSwordItem;
import net.mcreator.allaboutengie.item.RareShovelItem;
import net.mcreator.allaboutengie.item.RareSharkoClothItem;
import net.mcreator.allaboutengie.item.RareSharkItem;
import net.mcreator.allaboutengie.item.RarePickaxeItem;
import net.mcreator.allaboutengie.item.RareItem;
import net.mcreator.allaboutengie.item.RareHoeItem;
import net.mcreator.allaboutengie.item.RareAxeItem;
import net.mcreator.allaboutengie.item.PizzaSliceItem;
import net.mcreator.allaboutengie.item.OutragedEngiesItem;
import net.mcreator.allaboutengie.item.OutragedEngieShovelItem;
import net.mcreator.allaboutengie.item.OutragedEngiePlushItem;
import net.mcreator.allaboutengie.item.OutragedEngiePickaxeItem;
import net.mcreator.allaboutengie.item.OutragedEngieHoeItem;
import net.mcreator.allaboutengie.item.OutragedEngieEssenceItem;
import net.mcreator.allaboutengie.item.OutragedEngieBundleItem;
import net.mcreator.allaboutengie.item.OutragedEngieAxeItem;
import net.mcreator.allaboutengie.item.OperatorsShovelItem;
import net.mcreator.allaboutengie.item.OperatorsPickaxeItem;
import net.mcreator.allaboutengie.item.OperatorsItem;
import net.mcreator.allaboutengie.item.OperatorsHoeItem;
import net.mcreator.allaboutengie.item.OperatorsAxeItem;
import net.mcreator.allaboutengie.item.NetheriteOutragedEngiePlushItem;
import net.mcreator.allaboutengie.item.NetheriteInsanityPlushItem;
import net.mcreator.allaboutengie.item.NetheriteEnragedEngiePlushItem;
import net.mcreator.allaboutengie.item.NetheriteAngryEngiePlushItem;
import net.mcreator.allaboutengie.item.MythicSwordItem;
import net.mcreator.allaboutengie.item.MythicShovelItem;
import net.mcreator.allaboutengie.item.MythicSharkoClothItem;
import net.mcreator.allaboutengie.item.MythicSharkItem;
import net.mcreator.allaboutengie.item.MythicPickaxeItem;
import net.mcreator.allaboutengie.item.MythicItem;
import net.mcreator.allaboutengie.item.MythicHoeItem;
import net.mcreator.allaboutengie.item.MythicAxeItem;
import net.mcreator.allaboutengie.item.MonstrosityEngiesItem;
import net.mcreator.allaboutengie.item.MonstrosityEngieShovelItem;
import net.mcreator.allaboutengie.item.MonstrosityEngiePickaxeItem;
import net.mcreator.allaboutengie.item.MonstrosityEngieHoeItem;
import net.mcreator.allaboutengie.item.MonstrosityEngieEssenceItem;
import net.mcreator.allaboutengie.item.MonstrosityEngieBundleItem;
import net.mcreator.allaboutengie.item.MonstrosityEngieAxeItem;
import net.mcreator.allaboutengie.item.MonstrosityBanHammerPixelItem;
import net.mcreator.allaboutengie.item.MonstrosityBanHammerItem;
import net.mcreator.allaboutengie.item.MobsPlaqueItem;
import net.mcreator.allaboutengie.item.MiniBanHammerPixelItem;
import net.mcreator.allaboutengie.item.MiniBanHammerItem;
import net.mcreator.allaboutengie.item.MassiveBanHammerPixelItem;
import net.mcreator.allaboutengie.item.MassiveBanHammerItem;
import net.mcreator.allaboutengie.item.MadEngiePlushItem;
import net.mcreator.allaboutengie.item.LegendarySwordItem;
import net.mcreator.allaboutengie.item.LegendaryShovelItem;
import net.mcreator.allaboutengie.item.LegendarySharkoClothItem;
import net.mcreator.allaboutengie.item.LegendarySharkItem;
import net.mcreator.allaboutengie.item.LegendaryPickaxeItem;
import net.mcreator.allaboutengie.item.LegendaryItem;
import net.mcreator.allaboutengie.item.LegendaryHoeItem;
import net.mcreator.allaboutengie.item.LegendaryAxeItem;
import net.mcreator.allaboutengie.item.LargeBanHammerPixelItem;
import net.mcreator.allaboutengie.item.LargeBanHammerItem;
import net.mcreator.allaboutengie.item.KickBanHammerPixelItem;
import net.mcreator.allaboutengie.item.KickBanHammerItem;
import net.mcreator.allaboutengie.item.ItemsPlaqueItem;
import net.mcreator.allaboutengie.item.InsanityPlushItem;
import net.mcreator.allaboutengie.item.IdeagiverEngieBundleItem;
import net.mcreator.allaboutengie.item.HugeBanHammerPixelItem;
import net.mcreator.allaboutengie.item.HugeBanHammerItem;
import net.mcreator.allaboutengie.item.HotlineMiami2RunItem;
import net.mcreator.allaboutengie.item.HWGScytheItem;
import net.mcreator.allaboutengie.item.HWGItem;
import net.mcreator.allaboutengie.item.GoldenOutragedEngiePlushItem;
import net.mcreator.allaboutengie.item.GoldenInsanityPlushItem;
import net.mcreator.allaboutengie.item.GoldenEnragedEngiePlushItem;
import net.mcreator.allaboutengie.item.GoldenCookieItem;
import net.mcreator.allaboutengie.item.GoldenAngryEngiePlushItem;
import net.mcreator.allaboutengie.item.GiganticBanHammerPixelItem;
import net.mcreator.allaboutengie.item.GiganticBanHammerItem;
import net.mcreator.allaboutengie.item.ExtrasPlaqueItem;
import net.mcreator.allaboutengie.item.ExoticSwordItem;
import net.mcreator.allaboutengie.item.ExoticShovelItem;
import net.mcreator.allaboutengie.item.ExoticSharkoClothItem;
import net.mcreator.allaboutengie.item.ExoticSharkItem;
import net.mcreator.allaboutengie.item.ExoticPickaxeItem;
import net.mcreator.allaboutengie.item.ExoticItem;
import net.mcreator.allaboutengie.item.ExoticHoeItem;
import net.mcreator.allaboutengie.item.ExoticCookieItem;
import net.mcreator.allaboutengie.item.ExoticAxeItem;
import net.mcreator.allaboutengie.item.EpicSwordItem;
import net.mcreator.allaboutengie.item.EpicShovelItem;
import net.mcreator.allaboutengie.item.EpicSharkoClothItem;
import net.mcreator.allaboutengie.item.EpicSharkItem;
import net.mcreator.allaboutengie.item.EpicPickaxeItem;
import net.mcreator.allaboutengie.item.EpicItem;
import net.mcreator.allaboutengie.item.EpicHoeItem;
import net.mcreator.allaboutengie.item.EpicAxeItem;
import net.mcreator.allaboutengie.item.EnragedZombiesPlaqueItem;
import net.mcreator.allaboutengie.item.EnragedInsanityPlushItem;
import net.mcreator.allaboutengie.item.EnragedEngiesItem;
import net.mcreator.allaboutengie.item.EnragedEngieShovelItem;
import net.mcreator.allaboutengie.item.EnragedEngiePlushItem;
import net.mcreator.allaboutengie.item.EnragedEngiePickaxeItem;
import net.mcreator.allaboutengie.item.EnragedEngieHoeItem;
import net.mcreator.allaboutengie.item.EnragedEngieEssenceItem;
import net.mcreator.allaboutengie.item.EnragedEngieBundleItem;
import net.mcreator.allaboutengie.item.EnragedEngieAxeItem;
import net.mcreator.allaboutengie.item.EnragedCoinItem;
import net.mcreator.allaboutengie.item.EnormousBanHammerPixelItem;
import net.mcreator.allaboutengie.item.EnormousBanHammerItem;
import net.mcreator.allaboutengie.item.EngiesScythePixelItem;
import net.mcreator.allaboutengie.item.EngiesScytheItem;
import net.mcreator.allaboutengie.item.EngiesOwnEngieBundleItem;
import net.mcreator.allaboutengie.item.EngiesItem;
import net.mcreator.allaboutengie.item.EngiesBirthdayBundleItem;
import net.mcreator.allaboutengie.item.EngieShovelItem;
import net.mcreator.allaboutengie.item.EngieSharkoClothItem;
import net.mcreator.allaboutengie.item.EngieSharkItem;
import net.mcreator.allaboutengie.item.EngiePlushItem;
import net.mcreator.allaboutengie.item.EngiePlaqueItem;
import net.mcreator.allaboutengie.item.EngiePickaxeItem;
import net.mcreator.allaboutengie.item.EngieHoeItem;
import net.mcreator.allaboutengie.item.EngieGemItem;
import net.mcreator.allaboutengie.item.EngieCookieItem;
import net.mcreator.allaboutengie.item.EngieBundleItem;
import net.mcreator.allaboutengie.item.EngieAxeItem;
import net.mcreator.allaboutengie.item.EngiShovelItem;
import net.mcreator.allaboutengie.item.EngiPickaxeItem;
import net.mcreator.allaboutengie.item.EngiAxeItem;
import net.mcreator.allaboutengie.item.EnchantedGoldenCookieItem;
import net.mcreator.allaboutengie.item.EnchantedExoticCookieItem;
import net.mcreator.allaboutengie.item.EnchantedEngieCookieItem;
import net.mcreator.allaboutengie.item.EmptyCheesePuffsBinItem;
import net.mcreator.allaboutengie.item.EchdeathPixelItem;
import net.mcreator.allaboutengie.item.EchdeathItem;
import net.mcreator.allaboutengie.item.DoughWithSauceItem;
import net.mcreator.allaboutengie.item.DoughItem;
import net.mcreator.allaboutengie.item.DoomsDaysItem;
import net.mcreator.allaboutengie.item.DoomsDayShovelItem;
import net.mcreator.allaboutengie.item.DoomsDayScytheItem;
import net.mcreator.allaboutengie.item.DoomsDayPickaxeItem;
import net.mcreator.allaboutengie.item.DoomsDayHoeItem;
import net.mcreator.allaboutengie.item.DoomsDayCrucifixPixelItem;
import net.mcreator.allaboutengie.item.DoomsDayCrucifixItem;
import net.mcreator.allaboutengie.item.DoomsDayCoinItem;
import net.mcreator.allaboutengie.item.DoomsDayAxeItem;
import net.mcreator.allaboutengie.item.DimensionsPlaqueItem;
import net.mcreator.allaboutengie.item.DiamondOutragedEngiePlushItem;
import net.mcreator.allaboutengie.item.DiamondInsanityPlushItem;
import net.mcreator.allaboutengie.item.DiamondEnragedEngiePlushItem;
import net.mcreator.allaboutengie.item.DiamondAngryEngiePlushItem;
import net.mcreator.allaboutengie.item.DeveloperItem;
import net.mcreator.allaboutengie.item.DeveloperEngieBundleItem;
import net.mcreator.allaboutengie.item.DevEngiePlushItem;
import net.mcreator.allaboutengie.item.CyberbloodKatanaItem;
import net.mcreator.allaboutengie.item.CyberbloodItem;
import net.mcreator.allaboutengie.item.CyberbloodIngotItem;
import net.mcreator.allaboutengie.item.CyberbloodBattleAxeItem;
import net.mcreator.allaboutengie.item.CyberKatanaItem;
import net.mcreator.allaboutengie.item.CyberItem;
import net.mcreator.allaboutengie.item.CyberIngotItem;
import net.mcreator.allaboutengie.item.CrucifixPixelItem;
import net.mcreator.allaboutengie.item.CrucifixItem;
import net.mcreator.allaboutengie.item.CreativeEngieBundleItem;
import net.mcreator.allaboutengie.item.CookedPizzaItem;
import net.mcreator.allaboutengie.item.ContributorItem;
import net.mcreator.allaboutengie.item.ContentCreatorEngieBundleItem;
import net.mcreator.allaboutengie.item.CommonSwordItem;
import net.mcreator.allaboutengie.item.CommonShovelItem;
import net.mcreator.allaboutengie.item.CommonPickaxeItem;
import net.mcreator.allaboutengie.item.CommonItem;
import net.mcreator.allaboutengie.item.CommonHoeItem;
import net.mcreator.allaboutengie.item.CommonAxeItem;
import net.mcreator.allaboutengie.item.CodeRedeemersItem;
import net.mcreator.allaboutengie.item.CodeRedeemersHammerPixelItem;
import net.mcreator.allaboutengie.item.CodeRedeemersHammerItem;
import net.mcreator.allaboutengie.item.CheesePuffsUnopenedItem;
import net.mcreator.allaboutengie.item.CheesePuffsOpenedItem;
import net.mcreator.allaboutengie.item.CheeseItem;
import net.mcreator.allaboutengie.item.CheeseBallItem;
import net.mcreator.allaboutengie.item.ByeByeThereItem;
import net.mcreator.allaboutengie.item.BrowniesUnopenedItem;
import net.mcreator.allaboutengie.item.BrowniesOpenedItem;
import net.mcreator.allaboutengie.item.BrowniesEmptyItem;
import net.mcreator.allaboutengie.item.BrownieItem;
import net.mcreator.allaboutengie.item.BloodItem;
import net.mcreator.allaboutengie.item.BloodIngotItem;
import net.mcreator.allaboutengie.item.BloodBattleAxeItem;
import net.mcreator.allaboutengie.item.BigBanHammerPixelItem;
import net.mcreator.allaboutengie.item.BigBanHammerItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngiesItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngieShovelItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngiePickaxeItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngieHoeItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngieEssenceItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngieBundleItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngieBanHammerPixelItem;
import net.mcreator.allaboutengie.item.BiblicallyAccurateEngieAxeItem;
import net.mcreator.allaboutengie.item.BiblicallyAccuratEngieBanHammerItem;
import net.mcreator.allaboutengie.item.BanHammerPixelItem;
import net.mcreator.allaboutengie.item.BanHammerItem;
import net.mcreator.allaboutengie.item.BahemothBanHammerPixelItem;
import net.mcreator.allaboutengie.item.BahemothBanHammerItem;
import net.mcreator.allaboutengie.item.BagelItem;
import net.mcreator.allaboutengie.item.BagelCookedItem;
import net.mcreator.allaboutengie.item.BagelCheeseItem;
import net.mcreator.allaboutengie.item.BagelCheeseCookedItem;
import net.mcreator.allaboutengie.item.AngryEngiesItem;
import net.mcreator.allaboutengie.item.AngryEngieShovelItem;
import net.mcreator.allaboutengie.item.AngryEngiePlushItem;
import net.mcreator.allaboutengie.item.AngryEngiePickaxeItem;
import net.mcreator.allaboutengie.item.AngryEngieHoeItem;
import net.mcreator.allaboutengie.item.AngryEngieEssenceItem;
import net.mcreator.allaboutengie.item.AngryEngieBundleItem;
import net.mcreator.allaboutengie.item.AngryEngieAxeItem;
import net.mcreator.allaboutengie.item.AllAboutEngiePlaqueItem;
import net.mcreator.allaboutengie.item.AlbinoSharkoClothItem;
import net.mcreator.allaboutengie.item.AlbinoSharkItem;
import net.mcreator.allaboutengie.item.AAEEngieItem;
import net.mcreator.allaboutengie.item.AAEDevEngieItem;
import net.mcreator.allaboutengie.AllaboutengieMod;

public class AllaboutengieModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, AllaboutengieMod.MODID);
	public static final RegistryObject<Item> ENGIE_GEM = REGISTRY.register("engie_gem", () -> new EngieGemItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_ESSENCE = REGISTRY.register("angry_engie_essence", () -> new AngryEngieEssenceItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_ESSENCE = REGISTRY.register("enraged_engie_essence", () -> new EnragedEngieEssenceItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_ESSENCE = REGISTRY.register("outraged_engie_essence", () -> new OutragedEngieEssenceItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_ESSENCE = REGISTRY.register("biblically_accurate_engie_essence", () -> new BiblicallyAccurateEngieEssenceItem());
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_ESSENCE = REGISTRY.register("monstrosity_engie_essence", () -> new MonstrosityEngieEssenceItem());
	public static final RegistryObject<Item> CYBER_INGOT = REGISTRY.register("cyber_ingot", () -> new CyberIngotItem());
	public static final RegistryObject<Item> BLOOD_INGOT = REGISTRY.register("blood_ingot", () -> new BloodIngotItem());
	public static final RegistryObject<Item> CYBERBLOOD_INGOT = REGISTRY.register("cyberblood_ingot", () -> new CyberbloodIngotItem());
	public static final RegistryObject<Item> ENGIE_BLOCK = block(AllaboutengieModBlocks.ENGIE_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ANGRY_ENGIE_BLOCK = block(AllaboutengieModBlocks.ANGRY_ENGIE_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENRAGED_ENGIE_BLOCK = block(AllaboutengieModBlocks.ENRAGED_ENGIE_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> OUTRAGED_ENGIE_BLOCK = block(AllaboutengieModBlocks.OUTRAGED_ENGIE_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_BLOCK = block(AllaboutengieModBlocks.BIBLICALLY_ACCURATE_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_BLOCK = block(AllaboutengieModBlocks.MONSTROSITY_ENGIE_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> CYBER_BLOCK = block(AllaboutengieModBlocks.CYBER_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> BLOOD_BLOCK = block(AllaboutengieModBlocks.BLOOD_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> CYBERBLOOD_BLOCK = block(AllaboutengieModBlocks.CYBERBLOOD_BLOCK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> SHARKO_CLOTH = REGISTRY.register("sharko_cloth", () -> new SharkoClothItem());
	public static final RegistryObject<Item> ALBINO_SHARKO_CLOTH = REGISTRY.register("albino_sharko_cloth", () -> new AlbinoSharkoClothItem());
	public static final RegistryObject<Item> RARE_SHARKO_CLOTH = REGISTRY.register("rare_sharko_cloth", () -> new RareSharkoClothItem());
	public static final RegistryObject<Item> EPIC_SHARKO_CLOTH = REGISTRY.register("epic_sharko_cloth", () -> new EpicSharkoClothItem());
	public static final RegistryObject<Item> LEGENDARY_SHARKO_CLOTH = REGISTRY.register("legendary_sharko_cloth", () -> new LegendarySharkoClothItem());
	public static final RegistryObject<Item> MYTHIC_SHARKO_CLOTH = REGISTRY.register("mythic_sharko_cloth", () -> new MythicSharkoClothItem());
	public static final RegistryObject<Item> EXOTIC_SHARKO_CLOTH = REGISTRY.register("exotic_sharko_cloth", () -> new ExoticSharkoClothItem());
	public static final RegistryObject<Item> ENGIE_SHARKO_CLOTH = REGISTRY.register("engie_sharko_cloth", () -> new EngieSharkoClothItem());
	public static final RegistryObject<Item> ENGIE_AXE = REGISTRY.register("engie_axe", () -> new EngieAxeItem());
	public static final RegistryObject<Item> ENGIE_PICKAXE = REGISTRY.register("engie_pickaxe", () -> new EngiePickaxeItem());
	public static final RegistryObject<Item> ENGIE_SHOVEL = REGISTRY.register("engie_shovel", () -> new EngieShovelItem());
	public static final RegistryObject<Item> ENGIE_HOE = REGISTRY.register("engie_hoe", () -> new EngieHoeItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_AXE = REGISTRY.register("angry_engie_axe", () -> new AngryEngieAxeItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_PICKAXE = REGISTRY.register("angry_engie_pickaxe", () -> new AngryEngiePickaxeItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_SHOVEL = REGISTRY.register("angry_engie_shovel", () -> new AngryEngieShovelItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_HOE = REGISTRY.register("angry_engie_hoe", () -> new AngryEngieHoeItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_AXE = REGISTRY.register("enraged_engie_axe", () -> new EnragedEngieAxeItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_PICKAXE = REGISTRY.register("enraged_engie_pickaxe", () -> new EnragedEngiePickaxeItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_SHOVEL = REGISTRY.register("enraged_engie_shovel", () -> new EnragedEngieShovelItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_HOE = REGISTRY.register("enraged_engie_hoe", () -> new EnragedEngieHoeItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_AXE = REGISTRY.register("outraged_engie_axe", () -> new OutragedEngieAxeItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_PICKAXE = REGISTRY.register("outraged_engie_pickaxe", () -> new OutragedEngiePickaxeItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_SHOVEL = REGISTRY.register("outraged_engie_shovel", () -> new OutragedEngieShovelItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_HOE = REGISTRY.register("outraged_engie_hoe", () -> new OutragedEngieHoeItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_AXE = REGISTRY.register("biblically_accurate_engie_axe", () -> new BiblicallyAccurateEngieAxeItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_PICKAXE = REGISTRY.register("biblically_accurate_engie_pickaxe", () -> new BiblicallyAccurateEngiePickaxeItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_SHOVEL = REGISTRY.register("biblically_accurate_engie_shovel", () -> new BiblicallyAccurateEngieShovelItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_HOE = REGISTRY.register("biblically_accurate_engie_hoe", () -> new BiblicallyAccurateEngieHoeItem());
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_AXE = REGISTRY.register("monstrosity_engie_axe", () -> new MonstrosityEngieAxeItem());
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_PICKAXE = REGISTRY.register("monstrosity_engie_pickaxe", () -> new MonstrosityEngiePickaxeItem());
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_SHOVEL = REGISTRY.register("monstrosity_engie_shovel", () -> new MonstrosityEngieShovelItem());
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_HOE = REGISTRY.register("monstrosity_engie_hoe", () -> new MonstrosityEngieHoeItem());
	public static final RegistryObject<Item> DOOMS_DAY_SCYTHE = REGISTRY.register("dooms_day_scythe", () -> new DoomsDayScytheItem());
	public static final RegistryObject<Item> DOOMS_DAY_PICKAXE = REGISTRY.register("dooms_day_pickaxe", () -> new DoomsDayPickaxeItem());
	public static final RegistryObject<Item> DOOMS_DAY_AXE = REGISTRY.register("dooms_day_axe", () -> new DoomsDayAxeItem());
	public static final RegistryObject<Item> DOOMS_DAY_SHOVEL = REGISTRY.register("dooms_day_shovel", () -> new DoomsDayShovelItem());
	public static final RegistryObject<Item> DOOMS_DAY_HOE = REGISTRY.register("dooms_day_hoe", () -> new DoomsDayHoeItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_SCYTHE = REGISTRY.register("super_dooms_day_scythe", () -> new SuperDoomsDayScytheItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_PICKAXE = REGISTRY.register("super_dooms_day_pickaxe", () -> new SuperDoomsDayPickaxeItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_AXE = REGISTRY.register("super_dooms_day_axe", () -> new SuperDoomsDayAxeItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_SHOVEL = REGISTRY.register("super_dooms_day_shovel", () -> new SuperDoomsDayShovelItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_HOE = REGISTRY.register("super_dooms_day_hoe", () -> new SuperDoomsDayHoeItem());
	public static final RegistryObject<Item> COMMON_SWORD = REGISTRY.register("common_sword", () -> new CommonSwordItem());
	public static final RegistryObject<Item> COMMON_PICKAXE = REGISTRY.register("common_pickaxe", () -> new CommonPickaxeItem());
	public static final RegistryObject<Item> COMMON_AXE = REGISTRY.register("common_axe", () -> new CommonAxeItem());
	public static final RegistryObject<Item> COMMON_SHOVEL = REGISTRY.register("common_shovel", () -> new CommonShovelItem());
	public static final RegistryObject<Item> COMMON_HOE = REGISTRY.register("common_hoe", () -> new CommonHoeItem());
	public static final RegistryObject<Item> UNCOMMON_SWORD = REGISTRY.register("uncommon_sword", () -> new UncommonSwordItem());
	public static final RegistryObject<Item> UNCOMMON_PICKAXE = REGISTRY.register("uncommon_pickaxe", () -> new UncommonPickaxeItem());
	public static final RegistryObject<Item> UNCOMMON_AXE = REGISTRY.register("uncommon_axe", () -> new UncommonAxeItem());
	public static final RegistryObject<Item> UNCOMMON_SHOVEL = REGISTRY.register("uncommon_shovel", () -> new UncommonShovelItem());
	public static final RegistryObject<Item> UNCOMMON_HOE = REGISTRY.register("uncommon_hoe", () -> new UncommonHoeItem());
	public static final RegistryObject<Item> RARE_SWORD = REGISTRY.register("rare_sword", () -> new RareSwordItem());
	public static final RegistryObject<Item> RARE_PICKAXE = REGISTRY.register("rare_pickaxe", () -> new RarePickaxeItem());
	public static final RegistryObject<Item> RARE_AXE = REGISTRY.register("rare_axe", () -> new RareAxeItem());
	public static final RegistryObject<Item> RARE_SHOVEL = REGISTRY.register("rare_shovel", () -> new RareShovelItem());
	public static final RegistryObject<Item> RARE_HOE = REGISTRY.register("rare_hoe", () -> new RareHoeItem());
	public static final RegistryObject<Item> EPIC_SWORD = REGISTRY.register("epic_sword", () -> new EpicSwordItem());
	public static final RegistryObject<Item> EPIC_PICKAXE = REGISTRY.register("epic_pickaxe", () -> new EpicPickaxeItem());
	public static final RegistryObject<Item> EPIC_AXE = REGISTRY.register("epic_axe", () -> new EpicAxeItem());
	public static final RegistryObject<Item> EPIC_SHOVEL = REGISTRY.register("epic_shovel", () -> new EpicShovelItem());
	public static final RegistryObject<Item> EPIC_HOE = REGISTRY.register("epic_hoe", () -> new EpicHoeItem());
	public static final RegistryObject<Item> LEGENDARY_SWORD = REGISTRY.register("legendary_sword", () -> new LegendarySwordItem());
	public static final RegistryObject<Item> LEGENDARY_PICKAXE = REGISTRY.register("legendary_pickaxe", () -> new LegendaryPickaxeItem());
	public static final RegistryObject<Item> LEGENDARY_AXE = REGISTRY.register("legendary_axe", () -> new LegendaryAxeItem());
	public static final RegistryObject<Item> LEGENDARY_SHOVEL = REGISTRY.register("legendary_shovel", () -> new LegendaryShovelItem());
	public static final RegistryObject<Item> LEGENDARY_HOE = REGISTRY.register("legendary_hoe", () -> new LegendaryHoeItem());
	public static final RegistryObject<Item> MYTHIC_SWORD = REGISTRY.register("mythic_sword", () -> new MythicSwordItem());
	public static final RegistryObject<Item> MYTHIC_PICKAXE = REGISTRY.register("mythic_pickaxe", () -> new MythicPickaxeItem());
	public static final RegistryObject<Item> MYTHIC_AXE = REGISTRY.register("mythic_axe", () -> new MythicAxeItem());
	public static final RegistryObject<Item> MYTHIC_SHOVEL = REGISTRY.register("mythic_shovel", () -> new MythicShovelItem());
	public static final RegistryObject<Item> MYTHIC_HOE = REGISTRY.register("mythic_hoe", () -> new MythicHoeItem());
	public static final RegistryObject<Item> EXOTIC_SWORD = REGISTRY.register("exotic_sword", () -> new ExoticSwordItem());
	public static final RegistryObject<Item> EXOTIC_PICKAXE = REGISTRY.register("exotic_pickaxe", () -> new ExoticPickaxeItem());
	public static final RegistryObject<Item> EXOTIC_AXE = REGISTRY.register("exotic_axe", () -> new ExoticAxeItem());
	public static final RegistryObject<Item> EXOTIC_SHOVEL = REGISTRY.register("exotic_shovel", () -> new ExoticShovelItem());
	public static final RegistryObject<Item> EXOTIC_HOE = REGISTRY.register("exotic_hoe", () -> new ExoticHoeItem());
	public static final RegistryObject<Item> UNOBTAINIUM_SWORD = REGISTRY.register("unobtainium_sword", () -> new UnobtainiumSwordItem());
	public static final RegistryObject<Item> UNOBTAINIUM_PICKAXE = REGISTRY.register("unobtainium_pickaxe", () -> new UnobtainiumPickaxeItem());
	public static final RegistryObject<Item> UNOBTAINIUM_AXE = REGISTRY.register("unobtainium_axe", () -> new UnobtainiumAxeItem());
	public static final RegistryObject<Item> UNOBTAINIUM_SHOVEL = REGISTRY.register("unobtainium_shovel", () -> new UnobtainiumShovelItem());
	public static final RegistryObject<Item> UNOBTAINIUM_HOE = REGISTRY.register("unobtainium_hoe", () -> new UnobtainiumHoeItem());
	public static final RegistryObject<Item> ENGI_AXE = REGISTRY.register("engi_axe", () -> new EngiAxeItem());
	public static final RegistryObject<Item> ENGI_PICKAXE = REGISTRY.register("engi_pickaxe", () -> new EngiPickaxeItem());
	public static final RegistryObject<Item> ENGI_SHOVEL = REGISTRY.register("engi_shovel", () -> new EngiShovelItem());
	public static final RegistryObject<Item> CYBER_KATANA = REGISTRY.register("cyber_katana", () -> new CyberKatanaItem());
	public static final RegistryObject<Item> CYBERBLOOD_KATANA = REGISTRY.register("cyberblood_katana", () -> new CyberbloodKatanaItem());
	public static final RegistryObject<Item> BLOOD_BATTLE_AXE = REGISTRY.register("blood_battle_axe", () -> new BloodBattleAxeItem());
	public static final RegistryObject<Item> CYBERBLOOD_BATTLE_AXE = REGISTRY.register("cyberblood_battle_axe", () -> new CyberbloodBattleAxeItem());
	public static final RegistryObject<Item> CRUCIFIX = REGISTRY.register("crucifix", () -> new CrucifixItem());
	public static final RegistryObject<Item> DOOMS_DAY_CRUCIFIX = REGISTRY.register("dooms_day_crucifix", () -> new DoomsDayCrucifixItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_CRUCIFIX = REGISTRY.register("super_dooms_day_crucifix", () -> new SuperDoomsDayCrucifixItem());
	public static final RegistryObject<Item> UNOBTAINIUM_CHUNKLET = REGISTRY.register("unobtainium_chunklet", () -> new UnobtainiumChunkletItem());
	public static final RegistryObject<Item> UNOBTANIUM = REGISTRY.register("unobtanium", () -> new UnobtaniumItem());
	public static final RegistryObject<Item> METAL_CHEST = block(AllaboutengieModBlocks.METAL_CHEST, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_OAK = block(AllaboutengieModBlocks.METAL_CHEST_OAK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_DARK_OAK = block(AllaboutengieModBlocks.METAL_CHEST_DARK_OAK, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_SPRUCE = block(AllaboutengieModBlocks.METAL_CHEST_SPRUCE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_ACACIA = block(AllaboutengieModBlocks.METAL_CHEST_ACACIA, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_BIRCH = block(AllaboutengieModBlocks.METAL_CHEST_BIRCH, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_WARPED = block(AllaboutengieModBlocks.METAL_CHEST_WARPED, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_CRIMSON = block(AllaboutengieModBlocks.METAL_CHEST_CRIMSON, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_CHEST_JUNGLE = block(AllaboutengieModBlocks.METAL_CHEST_JUNGLE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> METAL_TABLE = block(AllaboutengieModBlocks.METAL_TABLE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> CYBER_ORE = block(AllaboutengieModBlocks.CYBER_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> BLOOD_ORE = block(AllaboutengieModBlocks.BLOOD_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENGIE_ORE = block(AllaboutengieModBlocks.ENGIE_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> DEEPSLATE_ENGIE_ORE = block(AllaboutengieModBlocks.DEEPSLATE_ENGIE_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> UNOBTAINIUM_ORE = block(AllaboutengieModBlocks.UNOBTAINIUM_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> DEEPSLATE_UNOBTAINIUM_ORE = block(AllaboutengieModBlocks.DEEPSLATE_UNOBTAINIUM_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> OLD_ENGIE_ORE = block(AllaboutengieModBlocks.OLD_ENGIE_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> OLD_DEEPSLATE_ENGIE_ORE = block(AllaboutengieModBlocks.OLD_DEEPSLATE_ENGIE_ORE, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENGIE_BUNDLE = REGISTRY.register("engie_bundle", () -> new EngieBundleItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_BUNDLE = REGISTRY.register("angry_engie_bundle", () -> new AngryEngieBundleItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_BUNDLE = REGISTRY.register("enraged_engie_bundle", () -> new EnragedEngieBundleItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_BUNDLE = REGISTRY.register("outraged_engie_bundle", () -> new OutragedEngieBundleItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_BUNDLE = REGISTRY.register("biblically_accurate_engie_bundle", () -> new BiblicallyAccurateEngieBundleItem());
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_BUNDLE = REGISTRY.register("monstrosity_engie_bundle", () -> new MonstrosityEngieBundleItem());
	public static final RegistryObject<Item> CREATIVE_ENGIE_BUNDLE = REGISTRY.register("creative_engie_bundle", () -> new CreativeEngieBundleItem());
	public static final RegistryObject<Item> ANGEL_HATTED_PRESENT = block(AllaboutengieModBlocks.ANGEL_HATTED_PRESENT, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> ENRAGED_COIN = REGISTRY.register("enraged_coin", () -> new EnragedCoinItem());
	public static final RegistryObject<Item> DOOMS_DAY_COIN = REGISTRY.register("dooms_day_coin", () -> new DoomsDayCoinItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_COIN = REGISTRY.register("super_dooms_day_coin", () -> new SuperDoomsDayCoinItem());
	public static final RegistryObject<Item> ANGRY_ENGIE_PLUSH = REGISTRY.register("angry_engie_plush", () -> new AngryEngiePlushItem());
	public static final RegistryObject<Item> ENRAGED_ENGIE_PLUSH = REGISTRY.register("enraged_engie_plush", () -> new EnragedEngiePlushItem());
	public static final RegistryObject<Item> OUTRAGED_ENGIE_PLUSH = REGISTRY.register("outraged_engie_plush", () -> new OutragedEngiePlushItem());
	public static final RegistryObject<Item> INSANITY_PLUSH = REGISTRY.register("insanity_plush", () -> new InsanityPlushItem());
	public static final RegistryObject<Item> GOLDEN_ANGRY_ENGIE_PLUSH = REGISTRY.register("golden_angry_engie_plush", () -> new GoldenAngryEngiePlushItem());
	public static final RegistryObject<Item> GOLDEN_ENRAGED_ENGIE_PLUSH = REGISTRY.register("golden_enraged_engie_plush", () -> new GoldenEnragedEngiePlushItem());
	public static final RegistryObject<Item> GOLDEN_OUTRAGED_ENGIE_PLUSH = REGISTRY.register("golden_outraged_engie_plush", () -> new GoldenOutragedEngiePlushItem());
	public static final RegistryObject<Item> GOLDEN_INSANITY_PLUSH = REGISTRY.register("golden_insanity_plush", () -> new GoldenInsanityPlushItem());
	public static final RegistryObject<Item> DIAMOND_ANGRY_ENGIE_PLUSH = REGISTRY.register("diamond_angry_engie_plush", () -> new DiamondAngryEngiePlushItem());
	public static final RegistryObject<Item> DIAMOND_ENRAGED_ENGIE_PLUSH = REGISTRY.register("diamond_enraged_engie_plush", () -> new DiamondEnragedEngiePlushItem());
	public static final RegistryObject<Item> DIAMOND_OUTRAGED_ENGIE_PLUSH = REGISTRY.register("diamond_outraged_engie_plush", () -> new DiamondOutragedEngiePlushItem());
	public static final RegistryObject<Item> DIAMOND_INSANITY_PLUSH = REGISTRY.register("diamond_insanity_plush", () -> new DiamondInsanityPlushItem());
	public static final RegistryObject<Item> NETHERITE_ANGRY_ENGIE_PLUSH = REGISTRY.register("netherite_angry_engie_plush", () -> new NetheriteAngryEngiePlushItem());
	public static final RegistryObject<Item> NETHERITE_ENRAGED_ENGIE_PLUSH = REGISTRY.register("netherite_enraged_engie_plush", () -> new NetheriteEnragedEngiePlushItem());
	public static final RegistryObject<Item> NETHERITE_OUTRAGED_ENGIE_PLUSH = REGISTRY.register("netherite_outraged_engie_plush", () -> new NetheriteOutragedEngiePlushItem());
	public static final RegistryObject<Item> NETHERITE_INSANITY_PLUSH = REGISTRY.register("netherite_insanity_plush", () -> new NetheriteInsanityPlushItem());
	public static final RegistryObject<Item> ENRAGED_INSANITY_PLUSH = REGISTRY.register("enraged_insanity_plush", () -> new EnragedInsanityPlushItem());
	public static final RegistryObject<Item> MAD_ENGIE_PLUSH = REGISTRY.register("mad_engie_plush", () -> new MadEngiePlushItem());
	public static final RegistryObject<Item> CHALLENGE_MODE_TROPHY_SOLO = block(AllaboutengieModBlocks.CHALLENGE_MODE_TROPHY_SOLO, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> CHALLENGE_MODE_TROPHY_MULTIPLAYER = block(AllaboutengieModBlocks.CHALLENGE_MODE_TROPHY_MULTIPLAYER, AllaboutengieModTabs.TAB_AAE_ITEMS_ITEMS);
	public static final RegistryObject<Item> MINI_BAN_HAMMER = REGISTRY.register("mini_ban_hammer", () -> new MiniBanHammerItem());
	public static final RegistryObject<Item> BAN_HAMMER = REGISTRY.register("ban_hammer", () -> new BanHammerItem());
	public static final RegistryObject<Item> BIG_BAN_HAMMER = REGISTRY.register("big_ban_hammer", () -> new BigBanHammerItem());
	public static final RegistryObject<Item> LARGE_BAN_HAMMER = REGISTRY.register("large_ban_hammer", () -> new LargeBanHammerItem());
	public static final RegistryObject<Item> HUGE_BAN_HAMMER = REGISTRY.register("huge_ban_hammer", () -> new HugeBanHammerItem());
	public static final RegistryObject<Item> ENORMOUS_BAN_HAMMER = REGISTRY.register("enormous_ban_hammer", () -> new EnormousBanHammerItem());
	public static final RegistryObject<Item> GIGANTIC_BAN_HAMMER = REGISTRY.register("gigantic_ban_hammer", () -> new GiganticBanHammerItem());
	public static final RegistryObject<Item> MASSIVE_BAN_HAMMER = REGISTRY.register("massive_ban_hammer", () -> new MassiveBanHammerItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_BAN_HAMMER = REGISTRY.register("biblically_accurate_engie_ban_hammer", () -> new BiblicallyAccuratEngieBanHammerItem());
	public static final RegistryObject<Item> MONSTROSITY_BAN_HAMMER = REGISTRY.register("monstrosity_ban_hammer", () -> new MonstrosityBanHammerItem());
	public static final RegistryObject<Item> MONSTROSITY_BAN_HAMMER_PIXEL = REGISTRY.register("monstrosity_ban_hammer_pixel", () -> new MonstrosityBanHammerPixelItem());
	public static final RegistryObject<Item> CRUCIFIX_PIXEL = REGISTRY.register("crucifix_pixel", () -> new CrucifixPixelItem());
	public static final RegistryObject<Item> MINI_BAN_HAMMER_PIXEL = REGISTRY.register("mini_ban_hammer_pixel", () -> new MiniBanHammerPixelItem());
	public static final RegistryObject<Item> BAN_HAMMER_PIXEL = REGISTRY.register("ban_hammer_pixel", () -> new BanHammerPixelItem());
	public static final RegistryObject<Item> BIG_BAN_HAMMER_PIXEL = REGISTRY.register("big_ban_hammer_pixel", () -> new BigBanHammerPixelItem());
	public static final RegistryObject<Item> LARGE_BAN_HAMMER_PIXEL = REGISTRY.register("large_ban_hammer_pixel", () -> new LargeBanHammerPixelItem());
	public static final RegistryObject<Item> HUGE_BAN_HAMMER_PIXEL = REGISTRY.register("huge_ban_hammer_pixel", () -> new HugeBanHammerPixelItem());
	public static final RegistryObject<Item> ENORMOUS_BAN_HAMMER_PIXEL = REGISTRY.register("enormous_ban_hammer_pixel", () -> new EnormousBanHammerPixelItem());
	public static final RegistryObject<Item> GIGANTIC_BAN_HAMMER_PIXEL = REGISTRY.register("gigantic_ban_hammer_pixel", () -> new GiganticBanHammerPixelItem());
	public static final RegistryObject<Item> MASSIVE_BAN_HAMMER_PIXEL = REGISTRY.register("massive_ban_hammer_pixel", () -> new MassiveBanHammerPixelItem());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_BAN_HAMMER_PIXEL = REGISTRY.register("biblically_accurate_engie_ban_hammer_pixel", () -> new BiblicallyAccurateEngieBanHammerPixelItem());
	public static final RegistryObject<Item> DOOMS_DAY_CRUCIFIX_PIXEL = REGISTRY.register("dooms_day_crucifix_pixel", () -> new DoomsDayCrucifixPixelItem());
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_CRUCIFIX_PIXEL = REGISTRY.register("super_dooms_day_crucifix_pixel", () -> new SuperDoomsDayCrucifixPixelItem());
	public static final RegistryObject<Item> GOLDEN_COOKIE = REGISTRY.register("golden_cookie", () -> new GoldenCookieItem());
	public static final RegistryObject<Item> ENCHANTED_GOLDEN_COOKIE = REGISTRY.register("enchanted_golden_cookie", () -> new EnchantedGoldenCookieItem());
	public static final RegistryObject<Item> EXOTIC_COOKIE = REGISTRY.register("exotic_cookie", () -> new ExoticCookieItem());
	public static final RegistryObject<Item> ENCHANTED_EXOTIC_COOKIE = REGISTRY.register("enchanted_exotic_cookie", () -> new EnchantedExoticCookieItem());
	public static final RegistryObject<Item> ENGIE_COOKIE = REGISTRY.register("engie_cookie", () -> new EngieCookieItem());
	public static final RegistryObject<Item> ENCHANTED_ENGIE_COOKIE = REGISTRY.register("enchanted_engie_cookie", () -> new EnchantedEngieCookieItem());
	public static final RegistryObject<Item> DOUGH = REGISTRY.register("dough", () -> new DoughItem());
	public static final RegistryObject<Item> DOUGH_WITH_SAUCE = REGISTRY.register("dough_with_sauce", () -> new DoughWithSauceItem());
	public static final RegistryObject<Item> UNCOOKED_PIZZA = REGISTRY.register("uncooked_pizza", () -> new UncookedPizzaItem());
	public static final RegistryObject<Item> COOKED_PIZZA = REGISTRY.register("cooked_pizza", () -> new CookedPizzaItem());
	public static final RegistryObject<Item> PIZZA_SLICE = REGISTRY.register("pizza_slice", () -> new PizzaSliceItem());
	public static final RegistryObject<Item> BAGEL = REGISTRY.register("bagel", () -> new BagelItem());
	public static final RegistryObject<Item> BAGEL_COOKED = REGISTRY.register("bagel_cooked", () -> new BagelCookedItem());
	public static final RegistryObject<Item> BAGEL_CHEESE = REGISTRY.register("bagel_cheese", () -> new BagelCheeseItem());
	public static final RegistryObject<Item> BAGEL_CHEESE_COOKED = REGISTRY.register("bagel_cheese_cooked", () -> new BagelCheeseCookedItem());
	public static final RegistryObject<Item> BROWNIES_UNOPENED = REGISTRY.register("brownies_unopened", () -> new BrowniesUnopenedItem());
	public static final RegistryObject<Item> BROWNIES_OPENED = REGISTRY.register("brownies_opened", () -> new BrowniesOpenedItem());
	public static final RegistryObject<Item> BROWNIE = REGISTRY.register("brownie", () -> new BrownieItem());
	public static final RegistryObject<Item> CHEESE_BALLS_UNOPENED = REGISTRY.register("cheese_balls_unopened", () -> new CheesePuffsUnopenedItem());
	public static final RegistryObject<Item> CHEESE_BALLS_OPENED = REGISTRY.register("cheese_balls_opened", () -> new CheesePuffsOpenedItem());
	public static final RegistryObject<Item> CHEESE_BALL = REGISTRY.register("cheese_ball", () -> new CheeseBallItem());
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> ENGIE_SPAWN_EGG = REGISTRY.register("engie_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE, -1559757, -12386431, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENGI_FR_SPAWN_EGG = REGISTRY.register("engi_fr_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGI_FR, -15921907, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> CREATOR_SPAWN_EGG = REGISTRY.register("creator_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.CREATOR, -6723841, -154, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> PROTOGEN_SPAWN_EGG = REGISTRY.register("protogen_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.PROTOGEN, -16737793, -16750951, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENGIE_GAMES_SPAWN_EGG = REGISTRY.register("engie_games_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE_GAMES, -1559757, -12386431, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> QUIZZET_SPAWN_EGG = REGISTRY.register("quizzet_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.QUIZZET, -1, -16777216, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIE_SPAWN_EGG = REGISTRY.register("biblically_accurate_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.BIBLICALLY_ACCURATE_ENGIE, -1, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> COMMON_ENGIE_SPAWN_EGG = REGISTRY.register("common_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.COMMON_ENGIE, -4310213, -5395027, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> MAD_ENGIE_SPAWN_EGG = REGISTRY.register("mad_engie_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.MAD_ENGIE, -3407872, -6044, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> UNCOMMON_ENGIE_SPAWN_EGG = REGISTRY.register("uncommon_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.UNCOMMON_ENGIE, -4310213, -10551397, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> RARE_ENGIE_SPAWN_EGG = REGISTRY.register("rare_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.RARE_ENGIE, -4310213, -10591233, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> EPIC_ENGIE_SPAWN_EGG = REGISTRY.register("epic_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.EPIC_ENGIE, -4310213, -2138369, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> LEGENDARY_ENGIE_SPAWN_EGG = REGISTRY.register("legendary_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.LEGENDARY_ENGIE, -4310213, -22178, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> MYTHIC_ENGIE_SPAWN_EGG = REGISTRY.register("mythic_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.MYTHIC_ENGIE, -4310213, -2162893, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> EXOTIC_ENGIE_SPAWN_EGG = REGISTRY.register("exotic_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.EXOTIC_ENGIE, -4310213, -11534368, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ANGRY_ENGIE_SPAWN_EGG = REGISTRY.register("angry_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ANGRY_ENGIE, -16777216, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ANGRY_ENGIE_STYLE_2_SPAWN_EGG = REGISTRY.register("angry_engie_style_2_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ANGRY_ENGIE_STYLE_2, -16777216, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENRAGED_ENGIE_SPAWN_EGG = REGISTRY.register("enraged_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_ENGIE, -16777216, -10092544, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENRAGED_ENGIE_STYLE_2_SPAWN_EGG = REGISTRY.register("enraged_engie_style_2_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_ENGIE_STYLE_2, -16777216, -10092544, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENRAGED_ENGIE_STYLE_3_SPAWN_EGG = REGISTRY.register("enraged_engie_style_3_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_ENGIE_STYLE_3, -16777216, -10092544, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> OUTRAGED_ENGIE_SPAWN_EGG = REGISTRY.register("outraged_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.OUTRAGED_ENGIE, -16777216, -9502465, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> OUTRAGED_ENGIE_STYLE_2_SPAWN_EGG = REGISTRY.register("outraged_engie_style_2_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.OUTRAGED_ENGIE_STYLE_2, -16777216, -9502465, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_SPAWN_EGG = REGISTRY.register("monstrosity_engie_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.MONSTROSITY_ENGIE, -16777216, -3010263, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ANGRY_ENGIE_SHARKO_SPAWN_EGG = REGISTRY.register("angry_engie_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ANGRY_ENGIE_SHARKO, -16777216, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENRAGED_ENGIE_SHARKO_SPAWN_EGG = REGISTRY.register("enraged_engie_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_ENGIE_SHARKO, -16777216, -10092544, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> OUTRAGED_ENGIE_SHARKO_SPAWN_EGG = REGISTRY.register("outraged_engie_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.OUTRAGED_ENGIE_SHARKO, -16777216, -9502465, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> MONSTROSITY_ENGIE_SHARKO_SPAWN_EGG = REGISTRY.register("monstrosity_engie_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.MONSTROSITY_ENGIE_SHARKO, -16777216, -3010263, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> DOOMS_DAY_SPAWN_EGG = REGISTRY.register("dooms_day_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.DOOMS_DAY, -15329770, -602330, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_SPAWN_EGG = REGISTRY.register("super_dooms_day_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.SUPER_DOOMS_DAY, -16250872, -602330, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> DOOMS_DAY_HOSTILE_SPAWN_EGG = REGISTRY.register("dooms_day_hostile_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.DOOMS_DAY_HOSTILE, -15329770, -602330, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> SUPER_DOOMS_DAY_HOSTILE_SPAWN_EGG = REGISTRY.register("super_dooms_day_hostile_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.SUPER_DOOMS_DAY_HOSTILE, -16250872, -602330, new Item.Properties().tab(AllaboutengieModTabs.TAB_MOBS)));
	public static final RegistryObject<Item> ENGIES_HELMET = REGISTRY.register("engies_helmet", () -> new EngiesItem.Helmet());
	public static final RegistryObject<Item> ENGIES_CHESTPLATE = REGISTRY.register("engies_chestplate", () -> new EngiesItem.Chestplate());
	public static final RegistryObject<Item> ENGIES_LEGGINGS = REGISTRY.register("engies_leggings", () -> new EngiesItem.Leggings());
	public static final RegistryObject<Item> ENGIES_BOOTS = REGISTRY.register("engies_boots", () -> new EngiesItem.Boots());
	public static final RegistryObject<Item> ANGRY_ENGIES_HELMET = REGISTRY.register("angry_engies_helmet", () -> new AngryEngiesItem.Helmet());
	public static final RegistryObject<Item> ANGRY_ENGIES_CHESTPLATE = REGISTRY.register("angry_engies_chestplate", () -> new AngryEngiesItem.Chestplate());
	public static final RegistryObject<Item> ANGRY_ENGIES_LEGGINGS = REGISTRY.register("angry_engies_leggings", () -> new AngryEngiesItem.Leggings());
	public static final RegistryObject<Item> ANGRY_ENGIES_BOOTS = REGISTRY.register("angry_engies_boots", () -> new AngryEngiesItem.Boots());
	public static final RegistryObject<Item> ENRAGED_ENGIES_HELMET = REGISTRY.register("enraged_engies_helmet", () -> new EnragedEngiesItem.Helmet());
	public static final RegistryObject<Item> ENRAGED_ENGIES_CHESTPLATE = REGISTRY.register("enraged_engies_chestplate", () -> new EnragedEngiesItem.Chestplate());
	public static final RegistryObject<Item> ENRAGED_ENGIES_LEGGINGS = REGISTRY.register("enraged_engies_leggings", () -> new EnragedEngiesItem.Leggings());
	public static final RegistryObject<Item> ENRAGED_ENGIES_BOOTS = REGISTRY.register("enraged_engies_boots", () -> new EnragedEngiesItem.Boots());
	public static final RegistryObject<Item> OUTRAGED_ENGIES_HELMET = REGISTRY.register("outraged_engies_helmet", () -> new OutragedEngiesItem.Helmet());
	public static final RegistryObject<Item> OUTRAGED_ENGIES_CHESTPLATE = REGISTRY.register("outraged_engies_chestplate", () -> new OutragedEngiesItem.Chestplate());
	public static final RegistryObject<Item> OUTRAGED_ENGIES_LEGGINGS = REGISTRY.register("outraged_engies_leggings", () -> new OutragedEngiesItem.Leggings());
	public static final RegistryObject<Item> OUTRAGED_ENGIES_BOOTS = REGISTRY.register("outraged_engies_boots", () -> new OutragedEngiesItem.Boots());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIES_HELMET = REGISTRY.register("biblically_accurate_engies_helmet", () -> new BiblicallyAccurateEngiesItem.Helmet());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIES_CHESTPLATE = REGISTRY.register("biblically_accurate_engies_chestplate", () -> new BiblicallyAccurateEngiesItem.Chestplate());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIES_LEGGINGS = REGISTRY.register("biblically_accurate_engies_leggings", () -> new BiblicallyAccurateEngiesItem.Leggings());
	public static final RegistryObject<Item> BIBLICALLY_ACCURATE_ENGIES_BOOTS = REGISTRY.register("biblically_accurate_engies_boots", () -> new BiblicallyAccurateEngiesItem.Boots());
	public static final RegistryObject<Item> MONSTROSITY_ENGIES_HELMET = REGISTRY.register("monstrosity_engies_helmet", () -> new MonstrosityEngiesItem.Helmet());
	public static final RegistryObject<Item> MONSTROSITY_ENGIES_CHESTPLATE = REGISTRY.register("monstrosity_engies_chestplate", () -> new MonstrosityEngiesItem.Chestplate());
	public static final RegistryObject<Item> MONSTROSITY_ENGIES_LEGGINGS = REGISTRY.register("monstrosity_engies_leggings", () -> new MonstrosityEngiesItem.Leggings());
	public static final RegistryObject<Item> MONSTROSITY_ENGIES_BOOTS = REGISTRY.register("monstrosity_engies_boots", () -> new MonstrosityEngiesItem.Boots());
	public static final RegistryObject<Item> DOOMS_DAYS_HELMET = REGISTRY.register("dooms_days_helmet", () -> new DoomsDaysItem.Helmet());
	public static final RegistryObject<Item> DOOMS_DAYS_CHESTPLATE = REGISTRY.register("dooms_days_chestplate", () -> new DoomsDaysItem.Chestplate());
	public static final RegistryObject<Item> DOOMS_DAYS_LEGGINGS = REGISTRY.register("dooms_days_leggings", () -> new DoomsDaysItem.Leggings());
	public static final RegistryObject<Item> DOOMS_DAYS_BOOTS = REGISTRY.register("dooms_days_boots", () -> new DoomsDaysItem.Boots());
	public static final RegistryObject<Item> SUPER_DOOMS_DAYS_HELMET = REGISTRY.register("super_dooms_days_helmet", () -> new SuperDoomsDaysItem.Helmet());
	public static final RegistryObject<Item> SUPER_DOOMS_DAYS_CHESTPLATE = REGISTRY.register("super_dooms_days_chestplate", () -> new SuperDoomsDaysItem.Chestplate());
	public static final RegistryObject<Item> SUPER_DOOMS_DAYS_LEGGINGS = REGISTRY.register("super_dooms_days_leggings", () -> new SuperDoomsDaysItem.Leggings());
	public static final RegistryObject<Item> SUPER_DOOMS_DAYS_BOOTS = REGISTRY.register("super_dooms_days_boots", () -> new SuperDoomsDaysItem.Boots());
	public static final RegistryObject<Item> SHARK_HELMET = REGISTRY.register("shark_helmet", () -> new SharkItem.Helmet());
	public static final RegistryObject<Item> SHARK_CHESTPLATE = REGISTRY.register("shark_chestplate", () -> new SharkItem.Chestplate());
	public static final RegistryObject<Item> SHARK_LEGGINGS = REGISTRY.register("shark_leggings", () -> new SharkItem.Leggings());
	public static final RegistryObject<Item> SHARK_BOOTS = REGISTRY.register("shark_boots", () -> new SharkItem.Boots());
	public static final RegistryObject<Item> ALBINO_SHARK_HELMET = REGISTRY.register("albino_shark_helmet", () -> new AlbinoSharkItem.Helmet());
	public static final RegistryObject<Item> ALBINO_SHARK_CHESTPLATE = REGISTRY.register("albino_shark_chestplate", () -> new AlbinoSharkItem.Chestplate());
	public static final RegistryObject<Item> ALBINO_SHARK_LEGGINGS = REGISTRY.register("albino_shark_leggings", () -> new AlbinoSharkItem.Leggings());
	public static final RegistryObject<Item> ALBINO_SHARK_BOOTS = REGISTRY.register("albino_shark_boots", () -> new AlbinoSharkItem.Boots());
	public static final RegistryObject<Item> RARE_SHARK_HELMET = REGISTRY.register("rare_shark_helmet", () -> new RareSharkItem.Helmet());
	public static final RegistryObject<Item> RARE_SHARK_CHESTPLATE = REGISTRY.register("rare_shark_chestplate", () -> new RareSharkItem.Chestplate());
	public static final RegistryObject<Item> RARE_SHARK_LEGGINGS = REGISTRY.register("rare_shark_leggings", () -> new RareSharkItem.Leggings());
	public static final RegistryObject<Item> RARE_SHARK_BOOTS = REGISTRY.register("rare_shark_boots", () -> new RareSharkItem.Boots());
	public static final RegistryObject<Item> EPIC_SHARK_HELMET = REGISTRY.register("epic_shark_helmet", () -> new EpicSharkItem.Helmet());
	public static final RegistryObject<Item> EPIC_SHARK_CHESTPLATE = REGISTRY.register("epic_shark_chestplate", () -> new EpicSharkItem.Chestplate());
	public static final RegistryObject<Item> EPIC_SHARK_LEGGINGS = REGISTRY.register("epic_shark_leggings", () -> new EpicSharkItem.Leggings());
	public static final RegistryObject<Item> EPIC_SHARK_BOOTS = REGISTRY.register("epic_shark_boots", () -> new EpicSharkItem.Boots());
	public static final RegistryObject<Item> LEGENDARY_SHARK_HELMET = REGISTRY.register("legendary_shark_helmet", () -> new LegendarySharkItem.Helmet());
	public static final RegistryObject<Item> LEGENDARY_SHARK_CHESTPLATE = REGISTRY.register("legendary_shark_chestplate", () -> new LegendarySharkItem.Chestplate());
	public static final RegistryObject<Item> LEGENDARY_SHARK_LEGGINGS = REGISTRY.register("legendary_shark_leggings", () -> new LegendarySharkItem.Leggings());
	public static final RegistryObject<Item> LEGENDARY_SHARK_BOOTS = REGISTRY.register("legendary_shark_boots", () -> new LegendarySharkItem.Boots());
	public static final RegistryObject<Item> MYTHIC_SHARK_HELMET = REGISTRY.register("mythic_shark_helmet", () -> new MythicSharkItem.Helmet());
	public static final RegistryObject<Item> MYTHIC_SHARK_CHESTPLATE = REGISTRY.register("mythic_shark_chestplate", () -> new MythicSharkItem.Chestplate());
	public static final RegistryObject<Item> MYTHIC_SHARK_LEGGINGS = REGISTRY.register("mythic_shark_leggings", () -> new MythicSharkItem.Leggings());
	public static final RegistryObject<Item> MYTHIC_SHARK_BOOTS = REGISTRY.register("mythic_shark_boots", () -> new MythicSharkItem.Boots());
	public static final RegistryObject<Item> EXOTIC_SHARK_HELMET = REGISTRY.register("exotic_shark_helmet", () -> new ExoticSharkItem.Helmet());
	public static final RegistryObject<Item> EXOTIC_SHARK_CHESTPLATE = REGISTRY.register("exotic_shark_chestplate", () -> new ExoticSharkItem.Chestplate());
	public static final RegistryObject<Item> EXOTIC_SHARK_LEGGINGS = REGISTRY.register("exotic_shark_leggings", () -> new ExoticSharkItem.Leggings());
	public static final RegistryObject<Item> EXOTIC_SHARK_BOOTS = REGISTRY.register("exotic_shark_boots", () -> new ExoticSharkItem.Boots());
	public static final RegistryObject<Item> ENGIE_SHARK_HELMET = REGISTRY.register("engie_shark_helmet", () -> new EngieSharkItem.Helmet());
	public static final RegistryObject<Item> ENGIE_SHARK_CHESTPLATE = REGISTRY.register("engie_shark_chestplate", () -> new EngieSharkItem.Chestplate());
	public static final RegistryObject<Item> ENGIE_SHARK_LEGGINGS = REGISTRY.register("engie_shark_leggings", () -> new EngieSharkItem.Leggings());
	public static final RegistryObject<Item> ENGIE_SHARK_BOOTS = REGISTRY.register("engie_shark_boots", () -> new EngieSharkItem.Boots());
	public static final RegistryObject<Item> COMMON_HELMET = REGISTRY.register("common_helmet", () -> new CommonItem.Helmet());
	public static final RegistryObject<Item> COMMON_CHESTPLATE = REGISTRY.register("common_chestplate", () -> new CommonItem.Chestplate());
	public static final RegistryObject<Item> COMMON_LEGGINGS = REGISTRY.register("common_leggings", () -> new CommonItem.Leggings());
	public static final RegistryObject<Item> COMMON_BOOTS = REGISTRY.register("common_boots", () -> new CommonItem.Boots());
	public static final RegistryObject<Item> UNCOMMON_HELMET = REGISTRY.register("uncommon_helmet", () -> new UncommonItem.Helmet());
	public static final RegistryObject<Item> UNCOMMON_CHESTPLATE = REGISTRY.register("uncommon_chestplate", () -> new UncommonItem.Chestplate());
	public static final RegistryObject<Item> UNCOMMON_LEGGINGS = REGISTRY.register("uncommon_leggings", () -> new UncommonItem.Leggings());
	public static final RegistryObject<Item> UNCOMMON_BOOTS = REGISTRY.register("uncommon_boots", () -> new UncommonItem.Boots());
	public static final RegistryObject<Item> RARE_HELMET = REGISTRY.register("rare_helmet", () -> new RareItem.Helmet());
	public static final RegistryObject<Item> RARE_CHESTPLATE = REGISTRY.register("rare_chestplate", () -> new RareItem.Chestplate());
	public static final RegistryObject<Item> RARE_LEGGINGS = REGISTRY.register("rare_leggings", () -> new RareItem.Leggings());
	public static final RegistryObject<Item> RARE_BOOTS = REGISTRY.register("rare_boots", () -> new RareItem.Boots());
	public static final RegistryObject<Item> EPIC_HELMET = REGISTRY.register("epic_helmet", () -> new EpicItem.Helmet());
	public static final RegistryObject<Item> EPIC_CHESTPLATE = REGISTRY.register("epic_chestplate", () -> new EpicItem.Chestplate());
	public static final RegistryObject<Item> EPIC_LEGGINGS = REGISTRY.register("epic_leggings", () -> new EpicItem.Leggings());
	public static final RegistryObject<Item> EPIC_BOOTS = REGISTRY.register("epic_boots", () -> new EpicItem.Boots());
	public static final RegistryObject<Item> LEGENDARY_HELMET = REGISTRY.register("legendary_helmet", () -> new LegendaryItem.Helmet());
	public static final RegistryObject<Item> LEGENDARY_CHESTPLATE = REGISTRY.register("legendary_chestplate", () -> new LegendaryItem.Chestplate());
	public static final RegistryObject<Item> LEGENDARY_LEGGINGS = REGISTRY.register("legendary_leggings", () -> new LegendaryItem.Leggings());
	public static final RegistryObject<Item> LEGENDARY_BOOTS = REGISTRY.register("legendary_boots", () -> new LegendaryItem.Boots());
	public static final RegistryObject<Item> MYTHIC_HELMET = REGISTRY.register("mythic_helmet", () -> new MythicItem.Helmet());
	public static final RegistryObject<Item> MYTHIC_CHESTPLATE = REGISTRY.register("mythic_chestplate", () -> new MythicItem.Chestplate());
	public static final RegistryObject<Item> MYTHIC_LEGGINGS = REGISTRY.register("mythic_leggings", () -> new MythicItem.Leggings());
	public static final RegistryObject<Item> MYTHIC_BOOTS = REGISTRY.register("mythic_boots", () -> new MythicItem.Boots());
	public static final RegistryObject<Item> EXOTIC_HELMET = REGISTRY.register("exotic_helmet", () -> new ExoticItem.Helmet());
	public static final RegistryObject<Item> EXOTIC_CHESTPLATE = REGISTRY.register("exotic_chestplate", () -> new ExoticItem.Chestplate());
	public static final RegistryObject<Item> EXOTIC_LEGGINGS = REGISTRY.register("exotic_leggings", () -> new ExoticItem.Leggings());
	public static final RegistryObject<Item> EXOTIC_BOOTS = REGISTRY.register("exotic_boots", () -> new ExoticItem.Boots());
	public static final RegistryObject<Item> UNOBTAINIUM_HELMET = REGISTRY.register("unobtainium_helmet", () -> new UnobtainiumItem.Helmet());
	public static final RegistryObject<Item> UNOBTAINIUM_CHESTPLATE = REGISTRY.register("unobtainium_chestplate", () -> new UnobtainiumItem.Chestplate());
	public static final RegistryObject<Item> UNOBTAINIUM_LEGGINGS = REGISTRY.register("unobtainium_leggings", () -> new UnobtainiumItem.Leggings());
	public static final RegistryObject<Item> UNOBTAINIUM_BOOTS = REGISTRY.register("unobtainium_boots", () -> new UnobtainiumItem.Boots());
	public static final RegistryObject<Item> CYBER_HELMET = REGISTRY.register("cyber_helmet", () -> new CyberItem.Helmet());
	public static final RegistryObject<Item> CYBER_CHESTPLATE = REGISTRY.register("cyber_chestplate", () -> new CyberItem.Chestplate());
	public static final RegistryObject<Item> CYBER_LEGGINGS = REGISTRY.register("cyber_leggings", () -> new CyberItem.Leggings());
	public static final RegistryObject<Item> CYBER_BOOTS = REGISTRY.register("cyber_boots", () -> new CyberItem.Boots());
	public static final RegistryObject<Item> BLOOD_HELMET = REGISTRY.register("blood_helmet", () -> new BloodItem.Helmet());
	public static final RegistryObject<Item> BLOOD_CHESTPLATE = REGISTRY.register("blood_chestplate", () -> new BloodItem.Chestplate());
	public static final RegistryObject<Item> BLOOD_LEGGINGS = REGISTRY.register("blood_leggings", () -> new BloodItem.Leggings());
	public static final RegistryObject<Item> BLOOD_BOOTS = REGISTRY.register("blood_boots", () -> new BloodItem.Boots());
	public static final RegistryObject<Item> CYBERBLOOD_HELMET = REGISTRY.register("cyberblood_helmet", () -> new CyberbloodItem.Helmet());
	public static final RegistryObject<Item> CYBERBLOOD_CHESTPLATE = REGISTRY.register("cyberblood_chestplate", () -> new CyberbloodItem.Chestplate());
	public static final RegistryObject<Item> CYBERBLOOD_LEGGINGS = REGISTRY.register("cyberblood_leggings", () -> new CyberbloodItem.Leggings());
	public static final RegistryObject<Item> CYBERBLOOD_BOOTS = REGISTRY.register("cyberblood_boots", () -> new CyberbloodItem.Boots());
	public static final RegistryObject<Item> SHARKO_SPAWN_EGG = REGISTRY.register("sharko_spawn_egg", () -> new ForgeSpawnEggItem(AllaboutengieModEntities.SHARKO, -12420148, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ALBINO_SHARKO_SPAWN_EGG = REGISTRY.register("albino_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ALBINO_SHARKO, -1644826, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> RARE_SHARKO_SPAWN_EGG = REGISTRY.register("rare_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.RARE_SHARKO, -12434740, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> EPIC_SHARKO_SPAWN_EGG = REGISTRY.register("epic_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.EPIC_SHARKO, -7077695, -5504795, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> LEGENDARY_SHARKO_SPAWN_EGG = REGISTRY.register("legendary_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.LEGENDARY_SHARKO, -12544, -7680, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> MYTHIC_SHARKO_SPAWN_EGG = REGISTRY.register("mythic_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.MYTHIC_SHARKO, -1512448, -196818, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> EXOTIC_SHARKO_SPAWN_EGG = REGISTRY.register("exotic_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.EXOTIC_SHARKO, -16714511, -12845059, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ENGIE_SHARKO_SPAWN_EGG = REGISTRY.register("engie_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE_SHARKO, -16250872, -7271155, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ENGIE_SHARKO_RARE_SPAWN_EGG = REGISTRY.register("engie_sharko_rare_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE_SHARKO_RARE, -1, -2788547, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> TIGER_SHARKO_SPAWN_EGG = REGISTRY.register("tiger_sharko_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.TIGER_SHARKO, -5329997, -13551280, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.SHARKO_APRIL_FOOLS, -12420148, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ALBINO_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("albino_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ALBINO_SHARKO_APRIL_FOOLS, -1644826, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> RARE_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("rare_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.RARE_SHARKO_APRIL_FOOLS, -12434740, -1, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> EPIC_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("epic_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.EPIC_SHARKO_APRIL_FOOLS, -7077695, -5504795, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> LEGENDARY_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("legendary_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.LEGENDARY_SHARKO_APRIL_FOOLS, -12544, -7680, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> MYTHIC_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("mythic_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.MYTHIC_SHARKO_APRIL_FOOLS, -1512448, -196818, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> EXOTIC_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("exotic_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.EXOTIC_SHARKO_APRIL_FOOLS, -16714511, -12845059, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ENGIE_SHARKO_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("engie_sharko_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE_SHARKO_APRIL_FOOLS, -16250872, -7271155, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ENGIE_SHARKO_RARE_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("engie_sharko_rare_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE_SHARKO_RARE_APRIL_FOOLS, -1, -2788547, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ENGIE_SHARKO_RARE_2_APRIL_FOOLS_SPAWN_EGG = REGISTRY.register("engie_sharko_rare_2_april_fools_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENGIE_SHARKO_RARE_2_APRIL_FOOLS, -5329997, -13551280, new Item.Properties().tab(AllaboutengieModTabs.TAB_SHARKOS)));
	public static final RegistryObject<Item> ENRAGED_NORMAL_SPAWN_EGG = REGISTRY.register("enraged_normal_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_NORMAL, -16358652, -7405568, new Item.Properties().tab(AllaboutengieModTabs.TAB_ZOMBIES)));
	public static final RegistryObject<Item> ENRAGED_TNT_SPAWN_EGG = REGISTRY.register("enraged_tnt_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_TNT, -2412774, -7405568, new Item.Properties().tab(AllaboutengieModTabs.TAB_ZOMBIES)));
	public static final RegistryObject<Item> ENRAGED_SPEED_SPAWN_EGG = REGISTRY.register("enraged_speed_spawn_egg",
			() -> new ForgeSpawnEggItem(AllaboutengieModEntities.ENRAGED_SPEED, -16489688, -7405568, new Item.Properties().tab(AllaboutengieModTabs.TAB_ZOMBIES)));
	public static final RegistryObject<Item> TRUE_BAN_HAMMER_NCMD = REGISTRY.register("true_ban_hammer_ncmd", () -> new TrueBanHammerNCMDItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER_NCMD_PIXEL = REGISTRY.register("true_ban_hammer_ncmd_pixel", () -> new TrueBanHammerNCMDPixelItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER = REGISTRY.register("true_ban_hammer", () -> new TrueBanHammerItem());
	public static final RegistryObject<Item> KICK_BAN_HAMMER = REGISTRY.register("kick_ban_hammer", () -> new KickBanHammerItem());
	public static final RegistryObject<Item> ECHDEATH = REGISTRY.register("echdeath", () -> new EchdeathItem());
	public static final RegistryObject<Item> TRUE_BAN_HAMMER_PIXEL = REGISTRY.register("true_ban_hammer_pixel", () -> new TrueBanHammerPixelItem());
	public static final RegistryObject<Item> KICK_BAN_HAMMER_PIXEL = REGISTRY.register("kick_ban_hammer_pixel", () -> new KickBanHammerPixelItem());
	public static final RegistryObject<Item> ECHDEATH_PIXEL = REGISTRY.register("echdeath_pixel", () -> new EchdeathPixelItem());
	public static final RegistryObject<Item> OPERATORS_HELMET = REGISTRY.register("operators_helmet", () -> new OperatorsItem.Helmet());
	public static final RegistryObject<Item> OPERATORS_CHESTPLATE = REGISTRY.register("operators_chestplate", () -> new OperatorsItem.Chestplate());
	public static final RegistryObject<Item> OPERATORS_LEGGINGS = REGISTRY.register("operators_leggings", () -> new OperatorsItem.Leggings());
	public static final RegistryObject<Item> OPERATORS_BOOTS = REGISTRY.register("operators_boots", () -> new OperatorsItem.Boots());
	public static final RegistryObject<Item> THANKS_FOR_PLAYING = block(AllaboutengieModBlocks.THANKS_FOR_PLAYING, null);
	public static final RegistryObject<Item> ENGIES_SCYTHE = REGISTRY.register("engies_scythe", () -> new EngiesScytheItem());
	public static final RegistryObject<Item> OPERATORS_AXE = REGISTRY.register("operators_axe", () -> new OperatorsAxeItem());
	public static final RegistryObject<Item> OPERATORS_PICKAXE = REGISTRY.register("operators_pickaxe", () -> new OperatorsPickaxeItem());
	public static final RegistryObject<Item> OPERATORS_SHOVEL = REGISTRY.register("operators_shovel", () -> new OperatorsShovelItem());
	public static final RegistryObject<Item> OPERATORS_HOE = REGISTRY.register("operators_hoe", () -> new OperatorsHoeItem());
	public static final RegistryObject<Item> EMPTY_CHEESE_BALLS_BIN = REGISTRY.register("empty_cheese_balls_bin", () -> new EmptyCheesePuffsBinItem());
	public static final RegistryObject<Item> DEVELOPER_HELMET = REGISTRY.register("developer_helmet", () -> new DeveloperItem.Helmet());
	public static final RegistryObject<Item> DEVELOPER_CHESTPLATE = REGISTRY.register("developer_chestplate", () -> new DeveloperItem.Chestplate());
	public static final RegistryObject<Item> DEVELOPER_LEGGINGS = REGISTRY.register("developer_leggings", () -> new DeveloperItem.Leggings());
	public static final RegistryObject<Item> DEVELOPER_BOOTS = REGISTRY.register("developer_boots", () -> new DeveloperItem.Boots());
	public static final RegistryObject<Item> IDEAGIVER_HELMET = REGISTRY.register("ideagiver_helmet", () -> new ContributorItem.Helmet());
	public static final RegistryObject<Item> IDEAGIVER_CHESTPLATE = REGISTRY.register("ideagiver_chestplate", () -> new ContributorItem.Chestplate());
	public static final RegistryObject<Item> IDEAGIVER_LEGGINGS = REGISTRY.register("ideagiver_leggings", () -> new ContributorItem.Leggings());
	public static final RegistryObject<Item> IDEAGIVER_BOOTS = REGISTRY.register("ideagiver_boots", () -> new ContributorItem.Boots());
	public static final RegistryObject<Item> TESTER_HELMET = REGISTRY.register("tester_helmet", () -> new TesterItem.Helmet());
	public static final RegistryObject<Item> TESTER_CHESTPLATE = REGISTRY.register("tester_chestplate", () -> new TesterItem.Chestplate());
	public static final RegistryObject<Item> TESTER_LEGGINGS = REGISTRY.register("tester_leggings", () -> new TesterItem.Leggings());
	public static final RegistryObject<Item> TESTER_BOOTS = REGISTRY.register("tester_boots", () -> new TesterItem.Boots());
	public static final RegistryObject<Item> AAE_ENGIE = REGISTRY.register("aae_engie", () -> new AAEEngieItem());
	public static final RegistryObject<Item> ITEMS_PLAQUE = REGISTRY.register("items_plaque", () -> new ItemsPlaqueItem());
	public static final RegistryObject<Item> MOBS_PLAQUE = REGISTRY.register("mobs_plaque", () -> new MobsPlaqueItem());
	public static final RegistryObject<Item> EXTRAS_PLAQUE = REGISTRY.register("extras_plaque", () -> new ExtrasPlaqueItem());
	public static final RegistryObject<Item> SHARKOS_PLAQUE = REGISTRY.register("sharkos_plaque", () -> new SharkosPlaqueItem());
	public static final RegistryObject<Item> DIMENSIONS_PLAQUE = REGISTRY.register("dimensions_plaque", () -> new DimensionsPlaqueItem());
	public static final RegistryObject<Item> ENRAGED_ZOMBIES_PLAQUE = REGISTRY.register("enraged_zombies_plaque", () -> new EnragedZombiesPlaqueItem());
	public static final RegistryObject<Item> ALL_ABOUT_ENGIE_PLAQUE = REGISTRY.register("all_about_engie_plaque", () -> new AllAboutEngiePlaqueItem());
	public static final RegistryObject<Item> THANKS_FOR_PLAYING_2 = block(AllaboutengieModBlocks.THANKS_FOR_PLAYING_2, null);
	public static final RegistryObject<Item> ENGIES_SCYTHE_PIXEL = REGISTRY.register("engies_scythe_pixel", () -> new EngiesScythePixelItem());
	public static final RegistryObject<Item> CODE_REDEEMERS_HAMMER = REGISTRY.register("code_redeemers_hammer", () -> new CodeRedeemersHammerItem());
	public static final RegistryObject<Item> CODE_REDEEMERS_HAMMER_PIXEL = REGISTRY.register("code_redeemers_hammer_pixel", () -> new CodeRedeemersHammerPixelItem());
	public static final RegistryObject<Item> CODE_REDEEMERS_HELMET = REGISTRY.register("code_redeemers_helmet", () -> new CodeRedeemersItem.Helmet());
	public static final RegistryObject<Item> CODE_REDEEMERS_CHESTPLATE = REGISTRY.register("code_redeemers_chestplate", () -> new CodeRedeemersItem.Chestplate());
	public static final RegistryObject<Item> CODE_REDEEMERS_LEGGINGS = REGISTRY.register("code_redeemers_leggings", () -> new CodeRedeemersItem.Leggings());
	public static final RegistryObject<Item> CODE_REDEEMERS_BOOTS = REGISTRY.register("code_redeemers_boots", () -> new CodeRedeemersItem.Boots());
	public static final RegistryObject<Item> THANKS_FOR_PLAYING_3 = block(AllaboutengieModBlocks.THANKS_FOR_PLAYING_3, null);
	public static final RegistryObject<Item> TEXTBOXYEAH = block(AllaboutengieModBlocks.TEXTBOXYEAH, null);
	public static final RegistryObject<Item> THANKS_FOR_PLAYING_4 = block(AllaboutengieModBlocks.THANKS_FOR_PLAYING_4, null);
	public static final RegistryObject<Item> AAE_DEV_ENGIE = REGISTRY.register("aae_dev_engie", () -> new AAEDevEngieItem());
	public static final RegistryObject<Item> BROWNIES_EMPTY = REGISTRY.register("brownies_empty", () -> new BrowniesEmptyItem());
	public static final RegistryObject<Item> COMICALLY_MASSIVE_BAN_HAMMER = REGISTRY.register("comically_massive_ban_hammer", () -> new BahemothBanHammerItem());
	public static final RegistryObject<Item> COMICALLY_MASSIVE_BAN_HAMMER_PIXEL = REGISTRY.register("comically_massive_ban_hammer_pixel", () -> new BahemothBanHammerPixelItem());
	public static final RegistryObject<Item> HWG_HELMET = REGISTRY.register("hwg_helmet", () -> new HWGItem.Helmet());
	public static final RegistryObject<Item> HWG_CHESTPLATE = REGISTRY.register("hwg_chestplate", () -> new HWGItem.Chestplate());
	public static final RegistryObject<Item> HWG_LEGGINGS = REGISTRY.register("hwg_leggings", () -> new HWGItem.Leggings());
	public static final RegistryObject<Item> HWG_BOOTS = REGISTRY.register("hwg_boots", () -> new HWGItem.Boots());
	public static final RegistryObject<Item> HWG_SCYTHE = REGISTRY.register("hwg_scythe", () -> new HWGScytheItem());
	public static final RegistryObject<Item> YOU_ARE_NOT_SUPPOSED_TO_HAVE_THIS = REGISTRY.register("you_are_not_supposed_to_have_this", () -> new YouAreNotSupposedToHaveThisItem());
	public static final RegistryObject<Item> ENGIE_PLUSH = REGISTRY.register("engie_plush", () -> new EngiePlushItem());
	public static final RegistryObject<Item> BYE_BYE_THERE = REGISTRY.register("bye_bye_there", () -> new ByeByeThereItem());
	public static final RegistryObject<Item> DEV_ENGIE_PLUSH = REGISTRY.register("dev_engie_plush", () -> new DevEngiePlushItem());
	public static final RegistryObject<Item> DEVELOPER_ENGIE_BUNDLE = REGISTRY.register("developer_engie_bundle", () -> new DeveloperEngieBundleItem());
	public static final RegistryObject<Item> IDEAGIVER_ENGIE_BUNDLE = REGISTRY.register("ideagiver_engie_bundle", () -> new IdeagiverEngieBundleItem());
	public static final RegistryObject<Item> TESTER_ENGIE_BUNDLE = REGISTRY.register("tester_engie_bundle", () -> new TesterEngieBundleItem());
	public static final RegistryObject<Item> CONTENT_CREATOR_ENGIE_BUNDLE = REGISTRY.register("content_creator_engie_bundle", () -> new ContentCreatorEngieBundleItem());
	public static final RegistryObject<Item> ENGIES_OWN_ENGIE_BUNDLE = REGISTRY.register("engies_own_engie_bundle", () -> new EngiesOwnEngieBundleItem());
	public static final RegistryObject<Item> ENGIE_PLAQUE = REGISTRY.register("engie_plaque", () -> new EngiePlaqueItem());
	public static final RegistryObject<Item> ENGIES_BIRTHDAY_BUNDLE25 = REGISTRY.register("engies_birthday_bundle25", () -> new EngiesBirthdayBundleItem());
	public static final RegistryObject<Item> HOTLINE_MIAMI_2_RUN = REGISTRY.register("hotline_miami_2_run", () -> new HotlineMiami2RunItem());
	public static final RegistryObject<Item> SPIKE_PART = block(AllaboutengieModBlocks.SPIKE_PART, null);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
