modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="allaboutengie"
version="2.21.25"
displayName="All About Engie"
credits="yuh"
displayURL="https://www.twitch.tv/engiegames"
logoFile="logo.png"
authors="[Dev]Engie(Games)"
description="Made with MCreator."

[[dependencies.allaboutengie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




