modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="allaboutengie"
version="6.1.25"
displayName="All About Engie"
credits="DevEngie(Games), MCreator, Family Members, and Grem."
displayURL="https://modrinth.com/user/DevEngie"
updateJSONURL="https://raw.githubusercontent.com/EngieGames/All-About-Engie/refs/heads/master/ModUpdateCheck.json"
logoFile="logo.png"
authors="DevEngie"
description="A collection of all my other mods for my 5th year of making mods! If you find issues, report them on the GitHub page for the mod please."

[[dependencies.allaboutengie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




